In [1]:
%load_ext autoreload
%autoreload 2

In [25]:
import numpy as np

from environment import CityModel, DefaultUpdateRules
from agent import RandomPlanner
import utils

In [ ]:
update_rules = DefaultUpdateRules()
model = CityModel(RandomPlanner, 10, 15, update_rules)

#let's try placing a tile

model.set_tile(5,1,utils.GREENERY)
model.set_tile(6,3,utils.RESIDENCE)
model.set_tile(9,4,utils.RESIDENCE)
model.set_tile(9,3,utils.RESIDENCE)
model.set_tile(8,3,utils.SERVICE)
print("City")
print(model.grid.tile._mesa_data)

model.update_rules.apply_rules(model)

print()
model.print_stats()

City
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0 0 0 0 0 0]]

=====Stats=====
Population: 5.0 / 30
Pollution: 0


In [47]:
import numpy as np
from scipy.ndimage import distance_transform_cdt

B = np.array([
    [0, 0, 0, 0, 0,0,0],
    [0, 1, 0, 0, 0,0,0],
    [0, 0, 0, 0, 0,0,0],
    [0, 0, 0, 1, 0,0,0],
    [0, 0, 0, 0, 0,0,0],
    [0, 0, 0, 0, 0,0,1],
], dtype=bool)

C = np.array([
    [0, 0, 0, 1, 0,0,0],
    [0, 0, 0, 0, 0,0,0],
    [0, 0, 1, 0, 0,0,0],
    [0, 0, 0, 0, 0,0,0],
    [0, 0, 0, 0, 0,1,0],
    [0, 0, 0, 0, 0,0,0],
], dtype=bool)


In [55]:
dist = distance_transform_cdt(~B, metric='chessboard')
print('Coverage')
print(dist)

print('affected')
affected = C*dist
print(affected)
(affected<=1) & (affected > 0)


Coverage
[[1 1 1 2 3 3 3]
 [1 0 1 2 2 2 3]
 [1 1 1 1 1 2 3]
 [2 2 1 0 1 2 2]
 [3 2 1 1 1 1 1]
 [3 2 2 2 2 1 0]]
affected
[[0 0 0 2 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0]]


array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False],
       [False, False, False, False, False, False, False]])